<?php

/*
|--------------------------------------------------------------------------
| Teaching samples
|--------------------------------------------------------------------------
|
| Six sequences, each engineered so that one specific thing becomes visible
| when it is run through the real service. They are not decoration and not
| test fixtures: they are the difference between a tool and a lesson.
|
| The sequences live in resources/samples and are generated by
| DNA-Backend/tools/build_samples.py, which refuses to write a file whose
| lesson has stopped working. If a change to the analysis or cloning services
| breaks one of these, that script says so before a class finds out.
|
| The titles and questions are translated in each locale's samples.php. The
| settings key pre-fills the form, so a reader who follows the link lands on
| the question rather than on an empty form they must configure correctly.
|
*/

return [

    'analysis' => [
        [
            'file' => 'gc-skew.fasta',
            'key' => 'gc_skew',
        ],
        [
            'file' => 'variants.fasta',
            'key' => 'variants',
        ],
        [
            'file' => 'reverse-strand-orf.fasta',
            'key' => 'reverse_orf',
        ],
        [
            'file' => 'ambiguous-bases.fasta',
            'key' => 'ambiguity',
        ],
    ],

    'cloning' => [
        [
            'file' => 'cloning-trap.fasta',
            'key' => 'cloning_trap',
            // The exercise only works if the reader arrives with these already
            // filled in. Asked to configure it themselves, most will pick a
            // different enzyme and never meet the trap.
            'settings' => [
                'panel' => 'teaching',
                'design_primers' => true,
                'target_start' => 20,
                'target_end' => 580,
                'forward_enzyme' => 'EcoRI',
                'reverse_enzyme' => 'XhoI',
            ],
        ],
        [
            'file' => 'plasmid-topology.fasta',
            'key' => 'plasmid_topology',
            'settings' => [
                'panel' => 'teaching',
                'design_primers' => false,
                'circular' => false,
            ],
        ],
    ],

];
